#!/bin/bash
#
# Build script - just to make life easier
#

xsysroot_profile="picute"
logfile="build.log"

if [ "$1" != "" ]; then
    xsysroot_profile=$1
fi

# Fix for finding dbus libraries from the host into the sysroot
export PKG_CONFIG_PATH="$(xsysroot -q sysroot)/usr/lib/arm-linux-gnueabihf/pkgconfig"
    
echo "Building picute - follow progress on $logfile"
python -u picute.py $xsysroot_profile --baptize > $logfile 2>&1

